Added the ability to use sshfs.
This will allow a client to use an attic on a remote host that
does not support attic. It will mount the remote host directory
specified using sshfs at /sshfs in the container.

diff --git a/start b/start
--- a/start
+++ b/start
@@ -17,4 +17,12 @@ fi
 chown -R root:root /root/.ssh
 chmod -R u=rwX,g=,o= /root/.ssh
 
+if [ -n "SSHFS" ] ; then
+    mkdir -p /sshfs
+    if ! sshfs "$SSHFS" /sshfs ; then
+        echo "Failed to mount sshfs: $SSHFS" >&2
+        exit 1
+    fi
+fi
+
 exec /usr/local/bin/attic "$@"
